import './components/deliv.js';
import './components/footer.js';
import './components/home.js';
import './components/maps.js';
import './components/menu.js';
import './components/navbar.js';
import './components/service.js';
import './utils/script.js';
import './utils/slick.min.js';
